package com.sermon.mynote.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

/**
 * NoteCategory generated by hbm2java
 */
@Entity
@Table(name = "notecategory")
public class NoteCategory implements java.io.Serializable {

	private Integer categoryId;
	private String category;

	public NoteCategory() {
	}

	public NoteCategory(String category) {
		this.category = category;
	}
   
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CategoryId")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

}
