package com.sermon.mynote.domain;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note")
public class Note implements java.io.Serializable {

	private Integer noteId;
	private int authorId;
	private String title;
	private String subTitle;
	private String introduction;
	private Date eventDate;
	private Date eventTime;
	private Integer categoryId;
	private String keywords;

	public Note() {
	}

	public Note(int authorId, String title) {
		this.authorId = authorId;
		this.title = title;
	}

	public Note(int authorId, String title, String subTitle,
			String introduction, Date eventDate, Date eventTime,
			Integer categoryId, String keywords) {
		this.authorId = authorId;
		this.title = title;
		this.subTitle = subTitle;
		this.introduction = introduction;
		this.eventDate = eventDate;
		this.eventTime = eventTime;
		this.categoryId = categoryId;
		this.keywords = keywords;
	}
   
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NoteId")
	public Integer getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Integer noteId) {
		this.noteId = noteId;
	}

	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

}
