package com.sermon.mynote.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "userprofile")
public class UserProfile implements java.io.Serializable {

	private Integer userProfileId;
	private Integer userId;
	private String firstName;
	private String lastName;
	private String nickName;
	private String address1;
	private String address2;
	private Integer cityId;
	private Integer stateId;
	private Integer countryId;
	private String zipCode;

	public UserProfile() {
	}

	public UserProfile(Integer userId, String firstName, String lastName,
			String nickName, String address1, String address2, Integer cityId,
			Integer stateId, Integer countryId, String zipCode) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nickName = nickName;
		this.address1 = address1;
		this.address2 = address2;
		this.cityId = cityId;
		this.stateId = stateId;
		this.countryId = countryId;
		this.zipCode = zipCode;
	}

	public Integer getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(Integer userProfileId) {
		this.userProfileId = userProfileId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserProfileID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

}
