
package com.sermon.mynote.domain;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

/**
 * UserFavorite generated by hbm2java
 */
@Entity
@NamedQuery(name = "UserFavorite.findUserFavByUserId", query = "SELECT o FROM UserFavorite o WHERE o.userId = (?1)")
@Table(name = "userfavorite")
public class UserFavorite implements java.io.Serializable {

	/**
	 * 
	 */

	private int userFavoriteId;
	private int userId;
	private int organizationId;

	public  UserFavorite() {

	}

	public UserFavorite(int userFavoriteId,int userId, int organizationId) {
	    this.userFavoriteId=userFavoriteId;
		this.userId = userId;
		this.organizationId = organizationId;
	}

	
	
	@Id
	@Column(name = "UserFavoriteKey")
	public int getUserFavoriteId() {
		return this.userFavoriteId;
	}

	public void setUserFavoriteId(int userFavoriteId) {
		this.userFavoriteId = userFavoriteId;
	}
   
	@Column(name = "UserID")
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "OrganizationId")
	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	

}
