package com.sermon.mynote.domain;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userEmail;
	private String userPwd;
	private String userStatus;
	private DateTime createDt;
	private DateTime updateDt;

	public User() {
	}

	public User(String userName, String userEmail, String userPwd,
			String userStatus) {
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPwd = userPwd;
		this.userStatus = userStatus;
	}

	public User(String userName, String userEmail, String userPwd,
			String userStatus, DateTime createDt, DateTime updateDt) {
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPwd = userPwd;
		this.userStatus = userStatus;
		this.createDt = createDt;
		this.updateDt = updateDt;
	}
  
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "Create_Dt")
	@Type(type="org.joda.time.contrib.hibernate.PersistentDateTime")
	//@DateTimeFormat(iso=ISO.DATE)
	public DateTime getCreateDt() {
		
		return this.createDt;
	}

	public void setCreateDt(DateTime createDt) {
		this.createDt = createDt;
	}
    
	@Column(name = "Update_Dt")
	@Type(type="org.joda.time.contrib.hibernate.PersistentDateTime")
	//@DateTimeFormat(iso=ISO.DATE)
	public DateTime getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(DateTime updateDt) {
		this.updateDt = updateDt;
	}

}
