package com.sermon.mynote.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedStoredProcedureQuery;
import javax.persistence.ParameterMode;
import javax.persistence.StoredProcedureParameter;
import javax.persistence.Table;

// Generated May 7, 2015 9:40:59 PM by Hibernate Tools 4.0.0

/**
 * UserProfile generated by hbm2java
 */



@Entity
@NamedStoredProcedureQuery(name = "UserProfile.update_userProfile", procedureName = "update_userProfile", parameters = {
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "userId", type = Integer.class),		
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "firstName", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "lastName", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "nickName", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "address1", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "address2", type = String.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "cityId", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "stateId", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "countryId", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "zipCode", type = String.class)
  //@StoredProcedureParameter(mode = ParameterMode.IN, name = "dob", type = Date.class),
 // @StoredProcedureParameter(mode = ParameterMode.IN, name = "gender", type = String.class)
})

@Table(name = "userprofile")
public class UserProfile implements java.io.Serializable {

	private Integer userProfileId;
	private Integer userId;
	private String firstName;
	private String lastName;
	private String nickName;
	private String address1;
	private String address2;
	private Integer cityId;
	private Integer stateId;
	private Integer countryId;
	private String zipCode;
	private Date DOB;
	private String Gender;

	public UserProfile() {
	}

	public UserProfile(Integer userId, String firstName, String lastName,
			String nickName, String address1, String address2, Integer cityId,
			Integer stateId, Integer countryId, String zipCode,Date dob,String gender) {
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.nickName = nickName;
		this.address1 = address1;
		this.address2 = address2;
		this.cityId = cityId;
		this.stateId = stateId;
		this.countryId = countryId;
		this.zipCode = zipCode;
		this.DOB=dob;
		this.Gender=gender;
	}

	public Integer getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(Integer userProfileId) {
		this.userProfileId = userProfileId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserProfileID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "Address_1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address_2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	public Integer getCountryId() {
		return this.countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public Date getDOB() {
		return DOB;
	}

	public void setDOB(Date dOB) {
		DOB = dOB;
	}

	public String getGender() {
		return Gender;
	}

	public void setGender(String gender) {
		Gender = gender;
	}

}
