package com.sermon.mynote.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * VwOrganizationNotesId generated by hbm2java
 */

@Entity

@NamedQuery(name = "VwOrganizationNotes.findSermonsByOrgId", query = "SELECT o FROM VwOrganizationNotes o  WHERE o.organizationid = (?1)")
@Table(name = "vw_OrganizationNotes")
public class VwOrganizationNotes implements java.io.Serializable {

	private int noteId;
	private int organizationid;
	private String organizationName;
	private String author;
	private String title;
	private Date eventDate;
	//private Date eventTime;

	public VwOrganizationNotes() {
	}

	public VwOrganizationNotes(int noteId, int organizationid, String author,
			String title) {
		this.noteId = noteId;
		this.organizationid = organizationid;
		this.author = author;
		this.title = title;
	}

	public VwOrganizationNotes(int noteId, int organizationid,
			String organizationName, String author, String title,
			Date eventDate, Date eventTime) {
		this.noteId = noteId;
		this.organizationid = organizationid;
		this.organizationName = organizationName;
		this.author = author;
		this.title = title;
		this.eventDate = eventDate;
		//this.eventTime = eventTime;
	}

	@Id
	@Column(name = "NoteId")
	public int getNoteId() {
		return this.noteId;
	}

	public void setNoteId(int noteId) {
		this.noteId = noteId;
	}

	public int getOrganizationid() {
		return this.organizationid;
	}

	public void setOrganizationid(int organizationid) {
		this.organizationid = organizationid;
	}

	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}
/*
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}
*/
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwOrganizationNotes))
			return false;
		VwOrganizationNotes castOther = (VwOrganizationNotes) other;

		return (this.getNoteId() == castOther.getNoteId())
				&& (this.getOrganizationid() == castOther.getOrganizationid())
				&& ((this.getOrganizationName() == castOther
						.getOrganizationName()) || (this.getOrganizationName() != null
						&& castOther.getOrganizationName() != null && this
						.getOrganizationName().equals(
								castOther.getOrganizationName())))
				&& ((this.getAuthor() == castOther.getAuthor()) || (this
						.getAuthor() != null && castOther.getAuthor() != null && this
						.getAuthor().equals(castOther.getAuthor())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getEventDate() == castOther.getEventDate()) || (this
						.getEventDate() != null
						&& castOther.getEventDate() != null && this
						.getEventDate().equals(castOther.getEventDate())))
		/*		&& ((this.getEventTime() == castOther.getEventTime()) || (this
						.getEventTime() != null
						&& castOther.getEventTime() != null && this
						.getEventTime().equals(castOther.getEventTime())))*/;
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNoteId();
		result = 37 * result + this.getOrganizationid();
		result = 37
				* result
				+ (getOrganizationName() == null ? 0 : this
						.getOrganizationName().hashCode());
		result = 37 * result
				+ (getAuthor() == null ? 0 : this.getAuthor().hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getEventDate() == null ? 0 : this.getEventDate().hashCode());
		/*result = 37 * result
				+ (getEventTime() == null ? 0 : this.getEventTime().hashCode());*/
		return result;
	}

}
